const ActionTypes = {
  UPDATE_NUMBER_OF_ATTENDEES: 'UPDATE_NUMBER_OF_ATTENDEES',
  UPDATE_AVERAGE_HOURLY_RATE: 'UPDATE_AVERAGE_HOURLY_RATE',
  UPDATE_CURRENCY: 'UPDATE_CURRENCY',
  MEETING_STARTED: 'MEETING_STARTED',
  MEETING_STOPPED: 'MEETING_STOPPED',
  GET_LOCATION: 'GET_LOCATION',
  GET_MEETINGS: 'GET_MEETINGS',
  ANY_GIVEN_ACTION: 'ANY_GIVEN_ACTION'
};

export default ActionTypes;
