const ActionTypes = {
  MEETING_STARTED: 'MEETING_STARTED',
  MEETING_STOPPED: 'MEETING_STOPPED',
  GET_LOCATION: 'GET_LOCATION',
  ANY_GIVEN_ACTION: 'ANY_GIVEN_ACTION'
};

export default ActionTypes;
